### ISSUE TITLE
Console is showing a useEffect Hook error 

### ISSUE THREAD

**Issue by Guneetsinghtuli** [Guneetsinghtuli/NewZ-application#2]
The useEffect hook of React is showing an error on console.

## Screenshot
![Screenshot 2021-09-19 at 8 00 40 PM](https://user-images.githubusercontent.com/48324492/133931567-76f8f4ae-696e-4efa-9eb8-936923ed3761.png)

**Comment by Ruberoni** [comment]
Hey @Guneetsinghtuli I came from Chingu, can I do and open a pull request for this issue? Let me know!

**Comment by Guneetsinghtuli** [comment]
**Yes @Ruberoni You can take up this issue and make a PR.** If you face any problem in installing it locally let me know
